[2024-10-30T15:01:33.318+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T15:01:33.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Predice-Stock-ML-Pipeline.store_ml_data_in_s3 manual__2024-10-30T14:27:23.134497+00:00 [queued]>
[2024-10-30T15:01:33.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Predice-Stock-ML-Pipeline.store_ml_data_in_s3 manual__2024-10-30T14:27:23.134497+00:00 [queued]>
[2024-10-30T15:01:33.364+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-10-30T15:01:33.373+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_ml_data_in_s3> on 2024-10-30 14:27:23.134497+00:00
[2024-10-30T15:01:33.383+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3525) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-30T15:01:33.384+0000] {standard_task_runner.py:63} INFO - Started process 3535 to run task
[2024-10-30T15:01:33.384+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Predice-Stock-ML-Pipeline', 'store_ml_data_in_s3', 'manual__2024-10-30T14:27:23.134497+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/stock_and_sentiment_ml_pipeline.py', '--cfg-path', '/tmp/tmp49g_rnxc']
[2024-10-30T15:01:33.386+0000] {standard_task_runner.py:91} INFO - Job 323: Subtask store_ml_data_in_s3
[2024-10-30T15:01:33.401+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-30T15:01:33.438+0000] {task_command.py:426} INFO - Running <TaskInstance: Predice-Stock-ML-Pipeline.store_ml_data_in_s3 manual__2024-10-30T14:27:23.134497+00:00 [running]> on host cf1c99cdc1a8
[2024-10-30T15:01:33.763+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Predice-Stock-ML-Pipeline' AIRFLOW_CTX_TASK_ID='store_ml_data_in_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T14:27:23.134497+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T14:27:23.134497+00:00'
[2024-10-30T15:01:33.765+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T15:01:34.714+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-30T15:01:38.087+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-30T15:01:38.088+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T15:01:38.101+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Predice-Stock-ML-Pipeline, task_id=store_ml_data_in_s3, run_id=manual__2024-10-30T14:27:23.134497+00:00, execution_date=20241030T142723, start_date=20241030T150133, end_date=20241030T150138
[2024-10-30T15:01:38.187+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-30T15:01:38.208+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T15:01:38.214+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
