[2024-10-29T20:29:40.431+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-29T20:29:40.461+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: feature_engineer_news_sentiment_data.store_engineered_sentiment_data_s3 manual__2024-10-29T20:26:36.369839+00:00 [queued]>
[2024-10-29T20:29:40.469+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: feature_engineer_news_sentiment_data.store_engineered_sentiment_data_s3 manual__2024-10-29T20:26:36.369839+00:00 [queued]>
[2024-10-29T20:29:40.470+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-29T20:29:40.480+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_engineered_sentiment_data_s3> on 2024-10-29 20:26:36.369839+00:00
[2024-10-29T20:29:40.493+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1635) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-29T20:29:40.494+0000] {standard_task_runner.py:63} INFO - Started process 1640 to run task
[2024-10-29T20:29:40.492+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'feature_engineer_news_sentiment_data', 'store_engineered_sentiment_data_s3', 'manual__2024-10-29T20:26:36.369839+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipelines.py', '--cfg-path', '/tmp/tmp45j55p7g']
[2024-10-29T20:29:40.496+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask store_engineered_sentiment_data_s3
[2024-10-29T20:29:40.516+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-29T20:29:40.562+0000] {task_command.py:426} INFO - Running <TaskInstance: feature_engineer_news_sentiment_data.store_engineered_sentiment_data_s3 manual__2024-10-29T20:26:36.369839+00:00 [running]> on host cf1c99cdc1a8
[2024-10-29T20:29:40.646+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='feature_engineer_news_sentiment_data' AIRFLOW_CTX_TASK_ID='store_engineered_sentiment_data_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T20:26:36.369839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T20:26:36.369839+00:00'
[2024-10-29T20:29:40.648+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-29T20:29:40.766+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-29T20:29:41.935+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-29T20:29:41.938+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-29T20:29:41.959+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=feature_engineer_news_sentiment_data, task_id=store_engineered_sentiment_data_s3, run_id=manual__2024-10-29T20:26:36.369839+00:00, execution_date=20241029T202636, start_date=20241029T202940, end_date=20241029T202941
[2024-10-29T20:29:42.024+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-29T20:29:42.045+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T20:29:42.047+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
