[2024-10-28T22:25:38.158+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-28T22:25:38.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_clean_technical_indicators_data.fetch_technical_indicators_data manual__2024-10-28T18:18:35.942088+00:00 [queued]>
[2024-10-28T22:25:38.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_clean_technical_indicators_data.fetch_technical_indicators_data manual__2024-10-28T18:18:35.942088+00:00 [queued]>
[2024-10-28T22:25:38.185+0000] {taskinstance.py:2306} INFO - Starting attempt 9 of 9
[2024-10-28T22:25:38.190+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_technical_indicators_data> on 2024-10-28 18:18:35.942088+00:00
[2024-10-28T22:25:38.197+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=22782) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-28T22:25:38.199+0000] {standard_task_runner.py:63} INFO - Started process 22784 to run task
[2024-10-28T22:25:38.198+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_clean_technical_indicators_data', 'fetch_technical_indicators_data', 'manual__2024-10-28T18:18:35.942088+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipelines.py', '--cfg-path', '/tmp/tmpoi46jv5c']
[2024-10-28T22:25:38.201+0000] {standard_task_runner.py:91} INFO - Job 106: Subtask fetch_technical_indicators_data
[2024-10-28T22:25:38.213+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-28T22:25:38.244+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_clean_technical_indicators_data.fetch_technical_indicators_data manual__2024-10-28T18:18:35.942088+00:00 [running]> on host 66a068bd0545
[2024-10-28T22:25:38.305+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_clean_technical_indicators_data' AIRFLOW_CTX_TASK_ID='fetch_technical_indicators_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T18:18:35.942088+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T18:18:35.942088+00:00'
[2024-10-28T22:25:38.306+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-28T22:25:39.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-28T22:25:39.180+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/stock_data_elt.py", line 116, in fetch_technical_indicators_data
    df = extract_indicator_data(data, indicator)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/stock_data_elt.py", line 137, in extract_indicator_data
    indicator_data = response_data[f'Technical Analysis: {indicator}']
                     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Technical Analysis: SMA'
[2024-10-28T22:25:39.219+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_and_clean_technical_indicators_data, task_id=fetch_technical_indicators_data, run_id=manual__2024-10-28T18:18:35.942088+00:00, execution_date=20241028T181835, start_date=20241028T222538, end_date=20241028T222539
[2024-10-28T22:25:39.235+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 106 for task fetch_technical_indicators_data ('Technical Analysis: SMA'; 22784)
[2024-10-28T22:25:39.276+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-28T22:25:39.297+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-28T22:25:39.300+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
