[2024-10-29T17:24:03.122+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-29T17:24:03.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_clean_technical_indicators_data.fetch_technical_indicators_data manual__2024-10-28T18:18:35.942088+00:00 [queued]>
[2024-10-29T17:24:03.161+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_clean_technical_indicators_data.fetch_technical_indicators_data manual__2024-10-28T18:18:35.942088+00:00 [queued]>
[2024-10-29T17:24:03.161+0000] {taskinstance.py:2306} INFO - Starting attempt 12 of 12
[2024-10-29T17:24:03.171+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_technical_indicators_data> on 2024-10-28 18:18:35.942088+00:00
[2024-10-29T17:24:03.182+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1203) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-29T17:24:03.184+0000] {standard_task_runner.py:63} INFO - Started process 1208 to run task
[2024-10-29T17:24:03.183+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_clean_technical_indicators_data', 'fetch_technical_indicators_data', 'manual__2024-10-28T18:18:35.942088+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipelines.py', '--cfg-path', '/tmp/tmpk7dphw99']
[2024-10-29T17:24:03.187+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask fetch_technical_indicators_data
[2024-10-29T17:24:03.209+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-29T17:24:03.259+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_clean_technical_indicators_data.fetch_technical_indicators_data manual__2024-10-28T18:18:35.942088+00:00 [running]> on host a5e3407ec3e4
[2024-10-29T17:24:03.386+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_clean_technical_indicators_data' AIRFLOW_CTX_TASK_ID='fetch_technical_indicators_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T18:18:35.942088+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T18:18:35.942088+00:00'
[2024-10-29T17:24:03.388+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-29T17:24:05.155+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-29T17:24:05.160+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/stock_data_elt.py", line 116, in fetch_technical_indicators_data
    df = extract_indicator_data(data, indicator)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/stock_data_elt.py", line 137, in extract_indicator_data
    indicator_data = response_data[f'Technical Analysis: {indicator}']
                     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Technical Analysis: SMA'
[2024-10-29T17:24:05.204+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_and_clean_technical_indicators_data, task_id=fetch_technical_indicators_data, run_id=manual__2024-10-28T18:18:35.942088+00:00, execution_date=20241028T181835, start_date=20241029T172403, end_date=20241029T172405
[2024-10-29T17:24:05.217+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 220 for task fetch_technical_indicators_data ('Technical Analysis: SMA'; 1208)
[2024-10-29T17:24:05.265+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-29T17:24:05.289+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T17:24:05.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
